import "primereact/resources/primereact.css"
import "primeflex/primeflex.css"
import "primeicons/primeicons.css"
import '../../src/styles/layout/layout.scss'
import "../styles/demo/Demos.scss"

import { LayoutProvider } from "../layout/context/layoutcontext"
import ReduxProvider from './reduxProvider'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link
          id="theme-css"
          href={`/themes/lara-light-indigo/theme.css`}
          rel="stylesheet"
        ></link>
      </head>
      <body>
        <ReduxProvider>
          <LayoutProvider>{children}</LayoutProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
