name: 배포

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: github action check
      run: |
        cd docker
        ls -al
    - name: EC2 Test
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        ls -al
        rm -f private_key.pem

